  1 - Undefined message error
  2 - Error opening output specification file
  3 - Error reading output specification file
  4 - Error opening a new data file - probably no space on disk
  5 - Error opening old data file
  6 - Error reading data file
  7 - Error writing data file
  8 - Error writing data file - hardware error
  9 - Invalid arguments for displaying data or no data in file
 10 - Record out of available data
 11 - Attempt to read past end of file
 12 - Attempt to write past end of file - writing on oldest data
 13 - 
 14 - 
 15 - 
 16 - 
 17 - 
 18 - The transceiver is defective or the installation is inadequate
 19 - Check your installation : too many spurious on Rass
 20 - You must increase HMIN
 21 - Failure attaching port number 0
 22 - Failure attaching port number 1
 23 - Failure attaching port number 2
 24 - Error in time and/or date format
 25 - 
 26 - Analog malfunction
 27 - Fatal error in COMMON buffer
 28 - Time is not sufficient for FFT
 29 - A division by zero has just occured
 30 - Interrupts are missing (check transceiver, A/D board, cable)
 31 - Error opening operating parameters' file before reading it
 32 - Error opening operating parameters' file before writing on it
 33 - An error has occured while sending characters to port number 0
 34 - An error has occured while sending characters to port number 1
 35 - An error has occured while sending characters to port number 2
 36 - First pause the system (PAUSE)
 37 - Too many characters per line
 38 - Printer fault. Printer is now off. Restart it with SEND command
 39 - Reading the data file. Please wait ...
 40 - Ready. Enter any valid Sodar parameter or order
 41 - Invalid transformation number
 42 - Out of screen limits
 43 - Out of transformation limits
 44 - Invalid color index (GCOLA, GPATA, GTEXA)
 45 - Invalid marker type
 46 - Too many data points (GPL, GPM, GPAT)
 47 - Invalid arrow head size. (0-1).
 48 - Invalid line type index
 49 - Invalid number of characters (GTEXA)
 50 - Not enough room for characters
 51 - Invalid number of characters (GTEXT)
 52 - Invalid or incompatible set of parameters (GDEWIN)
 53 - Invalid arrow length or invalid arrow length scale
 54 - Invalid rotation angle (GTEXA)
 55 - Invalid writing mode (GTEXA)
 56 - Invalid or incompatible set of parameters (GDEVIE)
 57 - Invalid number of points in data array or no validation
 58 - Invalid scale for arrow color (GVECFD)
 59 - Invalid axis type (GAXES)
 60 - Axis type inconsistent with corresponding scale value (GAXES)
 61 - Invalid date (TIMDAT)
 62 - Invalid plot type
 63 - X variable must be increasing
 64 - Slice must be positive. Probably trying to plot above NSDAY
 65 - Invalid or incompatible set of parameters (SCALE)
 66 - No validations
 67 - Warning: No validations for the color parameter (vector plot)
 68 - First pause the system (PAUSE) to modify this parameter
 69 - 
 70 - 
 71 - Error opening mailbox
 72 - 
 73 - 
 74 - Error reading system operating parameters
 75 - Error writing system operating parameters
 76 - Error reading system options
 77 - error writing system options
 78 - Error on timer handling
 79 - 
 80 - Error checking for a system PAUSE
 81 - 
 82 - 
 83 - Fatal ERROR
 84 - 
 85 - 
 86 - 
 87 - 
 88 - 
 89 - 
 90 - 
 91 - 
 92 - 
 93 - Protection key not found or demo period over
 94 - Too many fixed echoes on direct     beam 1 at layer    
 95 - Too many fixed echoes on direct     beam 2 at layer    
 96 - Too many fixed echoes on            beam 3 at layer
 97 - Too many fixed echoes on Symetrical beam 1 at layer
 98 - Too many fixed echoes on symetrical beam 2 at layer
 99 - Not enough space left on hard disk to save instantaneous file
100 - Error opening instantaneous data file
101 - Error writing instantaneous data file
102 - 
103 - 
104 - No more signal to the A/D board or defective A/D board
